---
title: "My Journey"
author: "Cynthia Kineza"
date: '2018-05-12'
output:
  pdf_document: default
  html_document: default
---


      
A short introduction on my career as a Data Scientist

#Education
     
      During my time at Johns Hopkins University, I was highly inspired by the ingenuity of people around me.
      Ideas were developed, theories challenged and critics made on the works of others. It was an environment of innovation and elevated creativity like nowhere else.
As someone looking constantly for challenges, highly motivated and a lifelong learner, the atmosphere stimulated my creativity. 

Collaboration was key and I took every opportunity that came my way.
With the required 64 units of coursework at the end of the first year, it was crucial to focus on the academic workload.

I quickly realized that I needed to be strategic and mindful of how I spent each hour of the day to be more productive.

After each lecture, I would try to read the material briefly, start working on homework assignments or projects. Furthermore, I worked as a teaching assistant and research assistant.

A lifelong drive for success helped me overcome the challenges that many graduate student faces. I would spend endless hours at the library but I did not mind, as I knew that preparation leads to opportunities. 

Occasionally, I would take breaks and explore the city with my friends from school so I could recharge mentally!

  
#Consulting projects


I belong to couple organizations: 

"DataKind" which is a community of scientists tackling various world problems using data science, working pro bono. Founded by Dr Jake Porway in the hopes of creating a world in which "every social organization has access to data capacity to better serve humanity"
There is also "Statistics Without Borders" which is as well a volunteer opportunity, that focuses more on providing “statistical consulting and assistance to organizations or governments to help deal with health issues”.

I recently started working on my first paid consulting project with a non-profit organization developing a Shiny app for survey analysis, which facilitates collection of data, and will lead to the statistical analysis.


#Recommendations

I would like to encourage anyone pursuing a data scientist career to take advantage of learning opportunities, and attend seminars. 
There are several data science boot camps that can enhance your knowledge.
One I would recommend is the Annual Summer Institute in Statistics for Big Data at the University of Washington organized by the School of Public Health. I attended one in 2017 and it was an amazing experience.
In addition, you can find data science Meetup groups in your area. Bouncing ideas with fellow statisticians is primordial, in my opinion.

I hope this was helpful.


Please feel free to comment bellow.

Thank you for your continued support!





